### ISSUE TITLE
bash: /src/github.com/tomnomnom/gf/gf-completion.bash: No such file or directory

### ISSUE THREAD

**Issue by JordRoest** [tomnomnom/gf#28]
root@kali:~# source ~/.bashrc
bash: /src/github.com/tomnomnom/gf/gf-completion.bash: No such file or directory
bash: /src/github.com/tomnomnom/gf/gf-completion.bash: No such file or directory
bash: /src/github.com/tomnomnom/gf/gf-completion.bash: No such file or directory
bash: /src/github.com/tomnomnom/gf/gf-completion.bash: No such file or directory

**Comment by unstabl3** [comment]
@kalihackerCD43 
your path for completion path is wrong!
it should be something like this:
/root/go/src/github.com/tomnomnom/gf/gf-completion.bash
where /root/go is your $GOPATH (it can be different in your case)

happy hacking!

**Comment by kalihackerCD43** [comment]
Thanks @unstabl3 ! its work, but if I open a new terminal than i get this:
`bash: /src/github.com/tomnomnom/gf/gf-completion.bash: No such file or directory
bash: /src/github.com/tomnomnom/gf/gf-completion.bash: No such file or directory
bash: /src/github.com/tomnomnom/gf/gf-completion.bash: No such file or directory
bash: /src/github.com/tomnomnom/gf/gf-completion.bash: No such file or directory
How can i fix this?
`

**Comment by unstabl3** [comment]
@kalihackerCD43, first of all, it would be good if you give some more details.
it looks like you are exporting it multiple times.
From the above errors, I can only tell you that you are not exporting "completion bash" with **$GOPATH**.
Also, read my previous comment again! (if you have used "go get" command to install you can find it under /root/go/...)
have a nice day!

**Comment by kalihackerCD43** [comment]
![Screenshot from 2020-01-08 09-58-07](https://user-images.githubusercontent.com/23139242/71964212-6f2e1780-31fd-11ea-9fee-91f36ac22860.png)

**Comment by unstabl3** [comment]
@kalihackerCD43 
All my previous comments are good enough to solve this issue..

**Comment by TH3PLUMB3R** [comment]
nano /root/.bashrc

**Comment by vasanthkumar007** [comment]
hi iam also getting same problem i dont know why 
1) go get -u github.com/tomnomnom/gf
2) echo 'source $GOPATH/src/github.com/tomnomnom/gf/gf-completion.bash' >> ~/.bashrc
3) source ~/.bashrc 
now i am getting
bash: /src/github.com/tomnomnom/gf/gf-completion.bash: No such file or directory
this error in terminal
![bash](https://user-images.githubusercontent.com/56502754/80134511-7ab30d80-8564-11ea-8a5d-47f45459366c.png)
![bash1](https://user-images.githubusercontent.com/56502754/80134514-7d156780-8564-11ea-8d49-7e88114135bf.png)

**Comment by unstabl3** [comment]
Hi,
This happened because your $GOPATH is not set!
two simple fixes for this
1) Set your GOPATH
2) and/or add the following line in your /root/.bashrc file
`source /root/go/src/github.com/tomnomnom/gf/gf-completion.bash`
I hope this will help!

-shubham

**Comment by Jawad-H** [comment]
echo 'source /root/go/src/github.com/tomnomnom/gf/gf-completion.bash' >> ~/.bashrc
solved

**Comment by fordrink** [comment]
`echo 'source $GOPATH/root/go/src/github.com/tomnomnom/gf/gf-completion.bash' >> ~/.bashrc `
Sloved

**Comment by Dev-Ayush-Mayank** [comment]
I am installing this in Windows 10.
This error is showing , how to resolve this $GOPATH what will come here ?
![1](https://user-images.githubusercontent.com/44479558/104806466-c34edd00-57fd-11eb-836a-63a874198941.PNG)

**Comment by fordrink** [comment]
nano .bashrc
add to # like this ( #source $GOPATH/root/go/src/github.com/tomnomnom/gf/gf-completion.bash )

**Comment by YBasin** [comment]
Hello, this worked for me 
locate /go/src/  --> /usr/local/go/src/ <=== this is my go/src location
and i added this to my .bashrc : source /usr/local/go/src/gf/gf-completion.bash
After that you have to create directory ".gf" in home and then copy the patterns 

Works in Ubuntu 20.04

**Comment by JohnRyk** [comment]
For new version go:

```shell
go install -v github.com/tomnomnom/gf@latest

updatedb
locate gf-completion.bash
```
Get the real path
and then change the path of  `gf-completion.bash` in ~/.bashrc

**Comment by c4ir0** [comment]
> For new version go:
> 
> ```shell
> go install -v github.com/tomnomnom/gf@latest
> 
> updatedb
> locate gf-completion.bash
> ```
> 
> Get the real path and then change the path of `gf-completion.bash` in ~/.bashrc

thx this really helped

**Comment by stissh834** [comment]
**1. Open the .bashrc or .bash_profile file:**
  nano ~/.bashrc or nano ~/.bash_profile

**2.Locate the problematic lines:**
source /home/ubuntu/go/src/github.com/tomnomnom/gf/gf-completion.bash
source /home/ubuntu/go/root/go/src/github.com/tomnomnom/gf/gf-completion.bash

**3. Comment out or remove the lines:**  _**You can comment out these lines by adding a # at the beginning:**_

#   # source /home/ubuntu/go/src/github.com/tomnomnom/gf/gf-completion.bash
#   # source /home/ubuntu/go/root/go/src/github.com/tomnomnom/gf/gf-completion.bash

**4. Save and exit:**
If you're using nano, save and exit by pressing CTRL + X, then Y to confirm, and Enter to save.

**5. Reload your shell configuration:**
source ~/.bashrc or source ~/.bash_profile

Thankyou

**Comment by Nil06** [comment]
If you encounter the following error after installing a Go package or tool (like MagicRecon or gf):

It typically means that the path to the gf-completion.bash script is incorrect or doesn't exist. Follow the steps below to fix the issue:

**1) Locate the gf-completion.bash File:**
Use the find command to locate the actual path where the gf-completion.bash file is installed:

`find / -name "gf-completion.bash" 2>/dev/null`

In most cases, it will be found under the Go module directory, something like:

`/home/your-username/go/pkg/mod/github.com/tomnomnom/gf@/gf-completion.bash`

**2) Update .bashrc**
Once you have the correct path, update the .bashrc file to source the correct path:

Open .bashrc with a text editor:

`nano ~/.bashrc`

Look for the line that sources gf-completion.bash and replace it with the correct path:

`source /home/your-username/go/pkg/mod/github.com/tomnomnom/gf@<version>/gf-completion.bash`

After saving and exiting the .bashrc file, reload it to apply the changes:

`source ~/.bashrc`

This guide should help anyone encountering the same issue. Feel free to share this on GitHub for the community!
