### ISSUE TITLE
Not showing the OUTPUT

### ISSUE THREAD

**Issue by PiyushThePal** [tomnomnom/gf#41]
I think I have installed this correctly as it isn't giving any error but after running it doesn't give any output.
So would like to know what can be the issue.
<img width="723" alt="Screenshot 2020-07-20 at 6 12 34 PM" src="https://user-images.githubusercontent.com/46394419/87938726-9f137d00-cab4-11ea-9d12-1c682fcd565c.png">

**Comment by Piyush-Paliwal** [comment]
#Hacktoberfest
