### ISSUE TITLE
name

### ISSUE THREAD

**Issue by c4ir0** [tomnomnom/gf#74]
why it's called gf I know g is for grep but what about the f

**Comment by kirisakow** [comment]
As Tom explains it himself in [this video (starting 10:27)](https://www.youtube.com/watch?v=l8iXMgk2nnY&t=10m27s):

> I'll often go grepping for lots of different things, so I have —surprise, surprise!— another tool called `gf`, which is short for “grep for”.

**Comment by c4ir0** [comment]
> As Tom explains it himself in [this video (starting 10:27)](https://www.youtube.com/watch?v=l8iXMgk2nnY&t=10m27s):
> 
> > I'll often go grepping for lots of different things, so I have —surprise, surprise!— another tool called `gf` (whi is short for “grep for”)

"grep for" unexpected 😂
